import { useState, useMemo } from 'react';
import { useLanguage } from '@/i18n/LanguageContext';
import { motion } from 'framer-motion';
import { BookOpen, Search } from 'lucide-react';
import { Input } from '@/components/ui/input';
import { Card, CardContent } from '@/components/ui/card';

const container = { hidden: { opacity: 0 }, show: { opacity: 1, transition: { staggerChildren: 0.02 } } };
const item = { hidden: { opacity: 0, y: 8 }, show: { opacity: 1, y: 0 } };

interface GlossaryEntry {
  term: string;
  definition: Record<string, string>;
  origin: Record<string, string>;
}

const g = (en: string, ru: string, it: string, es: string, ar: string, fr: string) => ({ en, ru, it, es, ar, fr });

const glossaryData: GlossaryEntry[] = [
  { term: 'A/B Testing',
    definition: g('A method of comparing two versions of a webpage or ad to determine which one performs better.','Метод сравнения двух версий веб-страницы или рекламы для определения, какая работает лучше.','Un metodo per confrontare due versioni di una pagina web o annuncio per determinare quale funziona meglio.','Un método para comparar dos versiones de una página web o anuncio para determinar cuál funciona mejor.','طريقة لمقارنة نسختين من صفحة ويب أو إعلان لتحديد أيهما أفضل أداءً.','Une méthode de comparaison de deux versions pour déterminer laquelle est la plus performante.'),
    origin: g('From statistical hypothesis testing; A and B represent the control and variant groups.','Из статистического тестирования гипотез; A и B обозначают контрольную и тестовую группы.','Dal test di ipotesi statistiche; A e B rappresentano i gruppi di controllo e variante.','De las pruebas de hipótesis estadísticas; A y B representan los grupos de control y variante.','من اختبار الفرضيات الإحصائية؛ A وB يمثلان مجموعتي التحكم والمتغير.','De l\'analyse statistique ; A et B représentent les groupes contrôle et variant.') },
  { term: 'Ad Copy',
    definition: g('The text used in an advertisement to persuade the audience to take action.','Текст, используемый в рекламе для убеждения аудитории совершить действие.','Il testo utilizzato in una pubblicità per persuadere il pubblico ad agire.','El texto utilizado en un anuncio para persuadir al público a tomar acción.','النص المستخدم في الإعلان لإقناع الجمهور باتخاذ إجراء.','Le texte utilisé dans une publicité pour persuader le public d\'agir.'),
    origin: g('From traditional advertising; "copy" refers to written content for publication.','Из традиционной рекламы; «copy» означает письменный контент для публикации.','Dalla pubblicità tradizionale; "copy" si riferisce al contenuto scritto per la pubblicazione.','De la publicidad tradicional; "copy" se refiere al contenido escrito para publicación.','من الإعلان التقليدي؛ "copy" يشير إلى المحتوى المكتوب للنشر.','De la publicité traditionnelle ; « copy » désigne le contenu écrit pour la publication.') },
  { term: 'Ad Frequency',
    definition: g('The average number of times a single user sees your ad over a given period.','Среднее количество раз, которое один пользователь видит вашу рекламу за определённый период.','Il numero medio di volte che un singolo utente vede il tuo annuncio in un dato periodo.','El número promedio de veces que un usuario ve tu anuncio en un período determinado.','متوسط عدد المرات التي يرى فيها مستخدم واحد إعلانك خلال فترة معينة.','Le nombre moyen de fois qu\'un utilisateur voit votre publicité sur une période donnée.'),
    origin: g('Broadcast media metric adapted for digital; helps measure ad fatigue.','Метрика из вещательных медиа, адаптированная для цифровой среды; помогает измерять усталость от рекламы.','Metrica dei media broadcast adattata al digitale; aiuta a misurare la fatica pubblicitaria.','Métrica de medios de transmisión adaptada para digital; ayuda a medir la fatiga publicitaria.','مقياس وسائط البث المتكيف للرقمية؛ يساعد في قياس إجهاد الإعلان.','Métrique des médias de diffusion adaptée au numérique ; aide à mesurer la lassitude publicitaire.') },
  { term: 'Ad Placement',
    definition: g('The specific location where an ad appears (e.g., news feed, stories, sidebar, search results).','Конкретное место, где показывается реклама (лента новостей, сторис, боковая панель, поисковая выдача).','La posizione specifica in cui appare un annuncio (feed, storie, barra laterale, risultati di ricerca).','La ubicación específica donde aparece un anuncio (feed, stories, barra lateral, resultados de búsqueda).','الموقع المحدد حيث يظهر الإعلان (خلاصة الأخبار، القصص، الشريط الجانبي، نتائج البحث).','L\'emplacement spécifique où apparaît une publicité (fil d\'actualité, stories, barre latérale, résultats de recherche).'),
    origin: g('From print media where placement referred to the physical position in a newspaper or magazine.','Из печатных СМИ, где размещение означало физическую позицию в газете или журнале.','Dai media stampati dove il posizionamento si riferiva alla posizione fisica in un giornale o rivista.','De los medios impresos donde la colocación se refería a la posición física en un periódico o revista.','من وسائل الإعلام المطبوعة حيث يشير الموضع إلى المكان الفعلي في صحيفة أو مجلة.','Des médias imprimés où le placement désignait la position physique dans un journal ou magazine.') },
  { term: 'Attribution',
    definition: g('The process of identifying which marketing touchpoints led to a conversion or sale.','Процесс определения, какие маркетинговые точки контакта привели к конверсии или продаже.','Il processo di identificazione di quali touchpoint di marketing hanno portato a una conversione o vendita.','El proceso de identificar qué puntos de contacto de marketing llevaron a una conversión o venta.','عملية تحديد نقاط الاتصال التسويقية التي أدت إلى التحويل أو البيع.','Le processus d\'identification des points de contact marketing ayant conduit à une conversion ou vente.'),
    origin: g('From analytics methodology; multi-touch attribution models became standard in the 2010s.','Из методологии аналитики; модели мультитач-атрибуции стали стандартом в 2010-х.','Dalla metodologia analitica; i modelli di attribuzione multi-touch sono diventati standard negli anni 2010.','De la metodología analítica; los modelos de atribución multi-touch se convirtieron en estándar en los 2010.','من منهجية التحليلات؛ أصبحت نماذج الإسناد متعددة اللمس معيارًا في العقد الثاني من الألفية.','De la méthodologie analytique ; les modèles d\'attribution multi-touch sont devenus standard dans les années 2010.') },
  { term: 'Audience Segmentation',
    definition: g('Dividing a target audience into subgroups based on shared characteristics like demographics, interests, or behavior.','Разделение целевой аудитории на подгруппы на основе общих характеристик: демографии, интересов или поведения.','Suddivisione del pubblico target in sottogruppi basati su caratteristiche condivise come dati demografici, interessi o comportamento.','División del público objetivo en subgrupos basados en características compartidas como demografía, intereses o comportamiento.','تقسيم الجمهور المستهدف إلى مجموعات فرعية بناءً على خصائص مشتركة مثل الديموغرافيا أو الاهتمامات أو السلوك.','Division du public cible en sous-groupes basés sur des caractéristiques communes comme la démographie, les intérêts ou le comportement.'),
    origin: g('Marketing strategy concept dating to the 1950s; adapted for precision targeting in digital advertising.','Концепция маркетинговой стратегии с 1950-х годов; адаптирована для точного таргетинга в цифровой рекламе.','Concetto di strategia di marketing risalente agli anni \'50; adattato per il targeting di precisione nella pubblicità digitale.','Concepto de estrategia de marketing de los años 50; adaptado para la segmentación precisa en publicidad digital.','مفهوم استراتيجية تسويقية يعود إلى الخمسينيات؛ تم تكييفه للاستهداف الدقيق في الإعلان الرقمي.','Concept de stratégie marketing datant des années 1950 ; adapté au ciblage de précision dans la publicité numérique.') },
  { term: 'Bid',
    definition: g('The maximum amount an advertiser is willing to pay for a click, impression, or action in an ad auction.','Максимальная сумма, которую рекламодатель готов заплатить за клик, показ или действие в рекламном аукционе.','L\'importo massimo che un inserzionista è disposto a pagare per un clic, un\'impressione o un\'azione in un\'asta pubblicitaria.','La cantidad máxima que un anunciante está dispuesto a pagar por un clic, impresión o acción en una subasta de anuncios.','الحد الأقصى للمبلغ الذي يرغب المعلن في دفعه مقابل نقرة أو ظهور أو إجراء في مزاد إعلاني.','Le montant maximum qu\'un annonceur est prêt à payer pour un clic, une impression ou une action dans une enchère publicitaire.'),
    origin: g('From auction theory; digital ad platforms adopted real-time bidding (RTB) in the late 2000s.','Из теории аукционов; платформы цифровой рекламы внедрили торги в реальном времени (RTB) в конце 2000-х.','Dalla teoria delle aste; le piattaforme pubblicitarie digitali hanno adottato le offerte in tempo reale (RTB) alla fine degli anni 2000.','De la teoría de subastas; las plataformas de anuncios digitales adoptaron las pujas en tiempo real (RTB) a finales de los 2000.','من نظرية المزادات؛ اعتمدت منصات الإعلان الرقمي المزايدة في الوقت الفعلي (RTB) في أواخر العقد الأول من الألفية.','De la théorie des enchères ; les plateformes publicitaires ont adopté les enchères en temps réel (RTB) à la fin des années 2000.') },
  { term: 'Bounce Rate',
    definition: g('The percentage of visitors who leave a website after viewing only one page without taking any action.','Процент посетителей, которые покидают сайт, просмотрев только одну страницу, не совершив действий.','La percentuale di visitatori che lasciano un sito web dopo aver visualizzato una sola pagina senza compiere alcuna azione.','El porcentaje de visitantes que abandonan un sitio web después de ver solo una página sin realizar ninguna acción.','النسبة المئوية للزوار الذين يغادرون موقع الويب بعد مشاهدة صفحة واحدة فقط دون اتخاذ أي إجراء.','Le pourcentage de visiteurs qui quittent un site web après avoir consulté une seule page sans effectuer d\'action.'),
    origin: g('Web analytics term popularized by Google Analytics; indicates landing page relevance.','Термин веб-аналитики, популяризированный Google Analytics; указывает на релевантность посадочной страницы.','Termine di analisi web reso popolare da Google Analytics; indica la pertinenza della pagina di destinazione.','Término de analítica web popularizado por Google Analytics; indica la relevancia de la página de destino.','مصطلح تحليلات الويب الذي شاعه Google Analytics؛ يشير إلى ملاءمة صفحة الهبوط.','Terme d\'analyse web popularisé par Google Analytics ; indique la pertinence de la page d\'atterrissage.') },
  { term: 'CPA (Cost Per Acquisition)',
    definition: g('The total cost of acquiring one customer through a specific campaign or channel.','Общая стоимость привлечения одного клиента через конкретную кампанию или канал.','Il costo totale per acquisire un cliente attraverso una campagna o un canale specifico.','El costo total de adquirir un cliente a través de una campaña o canal específico.','التكلفة الإجمالية للحصول على عميل واحد من خلال حملة أو قناة محددة.','Le coût total d\'acquisition d\'un client via une campagne ou un canal spécifique.'),
    origin: g('Digital marketing metric; measures efficiency of spend in converting prospects to customers.','Метрика цифрового маркетинга; измеряет эффективность расходов на конверсию потенциальных клиентов.','Metrica del marketing digitale; misura l\'efficienza della spesa nella conversione dei prospect in clienti.','Métrica de marketing digital; mide la eficiencia del gasto en la conversión de prospectos a clientes.','مقياس التسويق الرقمي؛ يقيس كفاءة الإنفاق في تحويل العملاء المحتملين إلى عملاء فعليين.','Métrique de marketing digital ; mesure l\'efficacité des dépenses pour convertir les prospects en clients.') },
  { term: 'CPC (Cost Per Click)',
    definition: g('The amount paid each time a user clicks on an ad. Calculated as total spend divided by number of clicks.','Сумма, которая оплачивается каждый раз, когда пользователь кликает по рекламе. Рассчитывается как общие расходы / клики.','L\'importo pagato ogni volta che un utente clicca su un annuncio. Calcolato come spesa totale divisa per il numero di clic.','La cantidad pagada cada vez que un usuario hace clic en un anuncio. Calculado como el gasto total dividido por clics.','المبلغ المدفوع في كل مرة ينقر فيها المستخدم على إعلان. يُحسب بقسمة إجمالي الإنفاق على عدد النقرات.','Le montant payé chaque fois qu\'un utilisateur clique sur une publicité. Calculé comme dépenses / clics.'),
    origin: g('Originated with pay-per-click advertising models pioneered by search engines in the early 2000s.','Возникло с моделями рекламы с оплатой за клик, введёнными поисковыми системами в начале 2000-х.','Originato dai modelli pubblicitari pay-per-click introdotti dai motori di ricerca nei primi anni 2000.','Se originó con los modelos de publicidad de pago por clic a principios de los 2000.','نشأ مع نماذج إعلانات الدفع بالنقرة التي قدمتها محركات البحث في أوائل الألفية.','Né avec les modèles publicitaires au coût par clic introduits par les moteurs de recherche au début des années 2000.') },
  { term: 'CPL (Cost Per Lead)',
    definition: g('The cost incurred for each lead generated. Calculated as total spend divided by number of leads.','Стоимость каждого полученного лида. Рассчитывается как общие расходы / количество лидов.','Il costo sostenuto per ogni lead generato. Calcolato come spesa totale divisa per il numero di lead.','El costo incurrido por cada lead generado. Calculado como gasto total / número de leads.','التكلفة المتكبدة لكل عميل محتمل تم توليده. تُحسب بقسمة إجمالي الإنفاق على عدد العملاء المحتملين.','Le coût engendré pour chaque lead généré. Calculé comme dépenses / nombre de leads.'),
    origin: g('Key performance metric in lead generation campaigns, especially in B2B marketing.','Ключевая метрика эффективности в кампаниях по генерации лидов, особенно в B2B маркетинге.','Metrica chiave nelle campagne di lead generation, soprattutto nel marketing B2B.','Métrica clave en campañas de generación de leads, especialmente en marketing B2B.','مقياس أداء رئيسي في حملات توليد العملاء المحتملين، خاصة في التسويق B2B.','Métrique clé dans les campagnes de génération de leads, surtout en marketing B2B.') },
  { term: 'CPM (Cost Per Mille)',
    definition: g('The cost per 1,000 impressions of an ad. Calculated as (spend / impressions) × 1000.','Стоимость за 1000 показов рекламы. Рассчитывается как (расходы / показы) × 1000.','Il costo per 1.000 impressioni di un annuncio. Calcolato come (spesa / impressioni) × 1000.','El costo por 1,000 impresiones de un anuncio. Calculado como (gasto / impresiones) × 1000.','التكلفة لكل 1,000 ظهور للإعلان. تُحسب كـ (الإنفاق / مرات الظهور) × 1000.','Le coût pour 1 000 impressions. Calculé comme (dépenses / impressions) × 1000.'),
    origin: g('"Mille" is Latin for "thousand." Adopted from traditional media buying where rates were quoted per thousand viewers.','"Mille" — латинское слово для "тысяча". Заимствовано из традиционной медиазакупки.','\"Mille\" è il latino per \"mille\". Adottato dall\'acquisto tradizionale di media.','"Mille" es latín para "mil". Adoptado de la compra de medios tradicional.','"Mille" كلمة لاتينية تعني "ألف". تم اعتمادها من شراء الوسائط التقليدية.','\"Mille\" vient du latin « mille ». Adopté de l\'achat média traditionnel.') },
  { term: 'Creative',
    definition: g('The visual and textual content of an ad, including images, videos, headlines, and copy.','Визуальный и текстовый контент рекламы, включая изображения, видео, заголовки и текст.','Il contenuto visivo e testuale di un annuncio, inclusi immagini, video, titoli e testo.','El contenido visual y textual de un anuncio, incluyendo imágenes, videos, titulares y texto.','المحتوى المرئي والنصي للإعلان، بما في ذلك الصور والفيديوهات والعناوين والنصوص.','Le contenu visuel et textuel d\'une publicité, incluant images, vidéos, titres et texte.'),
    origin: g('Advertising industry term; the "creative" distinguishes content creation from media buying.','Термин рекламной индустрии; «креатив» отличает создание контента от медиазакупки.','Termine del settore pubblicitario; il "creativo" distingue la creazione di contenuti dall\'acquisto di media.','Término de la industria publicitaria; el "creativo" distingue la creación de contenido de la compra de medios.','مصطلح في صناعة الإعلان؛ "الإبداعي" يميز إنشاء المحتوى عن شراء الوسائط.','Terme de l\'industrie publicitaire ; le « créatif » distingue la création de contenu de l\'achat média.') },
  { term: 'CTR (Click-Through Rate)',
    definition: g('The percentage of people who click on an ad after seeing it. Calculated as (clicks / impressions) × 100.','Процент людей, кликнувших по рекламе после просмотра. Рассчитывается как (клики / показы) × 100.','La percentuale di persone che cliccano su un annuncio dopo averlo visto. (clic / impressioni) × 100.','El porcentaje de personas que hacen clic en un anuncio después de verlo. (clics / impresiones) × 100.','النسبة المئوية للأشخاص الذين ينقرون على إعلان بعد مشاهدته. (النقرات / مرات الظهور) × 100.','Le pourcentage de personnes qui cliquent sur une publicité après l\'avoir vue. (clics / impressions) × 100.'),
    origin: g('One of the earliest digital advertising metrics, dating back to the first banner ad era in the mid-1990s.','Одна из первых метрик цифровой рекламы, восходящая к эпохе первых баннеров в середине 1990-х.','Una delle prime metriche della pubblicità digitale, risalente ai primi banner a metà anni \'90.','Una de las primeras métricas de publicidad digital, de mediados de los 90.','أحد أقدم مقاييس الإعلان الرقمي، يعود إلى منتصف التسعينيات.','L\'une des premières métriques publicitaires numériques, datant du milieu des années 1990.') },
  { term: 'Conversion',
    definition: g('When a user completes a desired action such as filling out a form, making a purchase, or signing up.','Когда пользователь совершает целевое действие: заполняет форму, совершает покупку или регистрируется.','Quando un utente completa un\'azione desiderata come compilare un modulo, effettuare un acquisto o registrarsi.','Cuando un usuario completa una acción deseada como llenar un formulario, comprar o registrarse.','عندما يكمل المستخدم إجراءً مرغوبًا مثل ملء نموذج أو الشراء أو التسجيل.','Lorsqu\'un utilisateur effectue une action souhaitée comme remplir un formulaire, acheter ou s\'inscrire.'),
    origin: g('Marketing term borrowed from sales; refers to converting a prospect into a customer or lead.','Маркетинговый термин из продаж; означает конверсию потенциального клиента в покупателя.','Termine di marketing preso dalle vendite; conversione di un prospect in cliente.','Término de marketing de ventas; convertir un prospecto en cliente.','مصطلح تسويقي من المبيعات؛ يشير إلى تحويل عميل محتمل إلى عميل فعلي.','Terme marketing emprunté aux ventes ; conversion d\'un prospect en client.') },
  { term: 'Conversion Rate',
    definition: g('The percentage of users who complete a desired action out of the total who interacted with the ad or page.','Процент пользователей, совершивших целевое действие, от общего числа взаимодействовавших с рекламой или страницей.','La percentuale di utenti che completano un\'azione desiderata rispetto al totale che ha interagito con l\'annuncio o la pagina.','El porcentaje de usuarios que completan una acción deseada del total que interactuó con el anuncio o página.','النسبة المئوية للمستخدمين الذين أكملوا إجراءً مرغوبًا من إجمالي من تفاعل مع الإعلان أو الصفحة.','Le pourcentage d\'utilisateurs ayant effectué une action souhaitée par rapport au total ayant interagi avec la publicité ou la page.'),
    origin: g('Fundamental e-commerce metric; the key indicator of landing page and funnel effectiveness.','Фундаментальная метрика электронной коммерции; ключевой показатель эффективности посадочных страниц и воронок.','Metrica fondamentale dell\'e-commerce; indicatore chiave dell\'efficacia della landing page.','Métrica fundamental del e-commerce; indicador clave de la efectividad de la página de destino.','مقياس أساسي للتجارة الإلكترونية؛ المؤشر الرئيسي لفعالية صفحة الهبوط.','Métrique fondamentale du e-commerce ; indicateur clé de l\'efficacité des pages d\'atterrissage.') },
  { term: 'CRO (Conversion Rate Optimization)',
    definition: g('The process of improving the percentage of website visitors who take a desired action.','Процесс улучшения процента посетителей сайта, совершающих целевое действие.','Il processo di miglioramento della percentuale di visitatori del sito che compiono un\'azione desiderata.','El proceso de mejorar el porcentaje de visitantes del sitio que realizan una acción deseada.','عملية تحسين النسبة المئوية لزوار الموقع الذين يتخذون إجراءً مرغوبًا.','Le processus d\'amélioration du pourcentage de visiteurs effectuant une action souhaitée.'),
    origin: g('Emerged as a discipline in the mid-2000s with tools like Optimizely and VWO.','Возникла как дисциплина в середине 2000-х с инструментами Optimizely и VWO.','Emersa come disciplina a metà degli anni 2000 con strumenti come Optimizely e VWO.','Surgió como disciplina a mediados de los 2000 con herramientas como Optimizely y VWO.','ظهر كتخصص في منتصف العقد الأول من الألفية مع أدوات مثل Optimizely وVWO.','Apparue comme discipline au milieu des années 2000 avec des outils comme Optimizely et VWO.') },
  { term: 'DPA (Dynamic Product Ads)',
    definition: g('Ads that automatically show products from your catalog based on user behavior and interests.','Реклама, которая автоматически показывает товары из каталога на основе поведения и интересов пользователей.','Annunci che mostrano automaticamente prodotti dal tuo catalogo basandosi sul comportamento e gli interessi degli utenti.','Anuncios que muestran automáticamente productos de tu catálogo basándose en el comportamiento e intereses del usuario.','إعلانات تعرض تلقائيًا منتجات من كتالوجك بناءً على سلوك المستخدم واهتماماته.','Publicités qui affichent automatiquement des produits de votre catalogue selon le comportement et les intérêts de l\'utilisateur.'),
    origin: g('Pioneered by Facebook (Meta) in 2015; revolutionized e-commerce advertising with automated product feeds.','Представлены Facebook (Meta) в 2015 году; революционизировали рекламу электронной коммерции.','Introdotti da Facebook (Meta) nel 2015; hanno rivoluzionato la pubblicità e-commerce.','Introducidos por Facebook (Meta) en 2015; revolucionaron la publicidad de e-commerce.','قدمها Facebook (Meta) في 2015؛ أحدثت ثورة في إعلانات التجارة الإلكترونية.','Introduites par Facebook (Meta) en 2015 ; ont révolutionné la publicité e-commerce.') },
  { term: 'Engagement Rate',
    definition: g('The percentage of users who interact with content (likes, comments, shares, clicks) relative to total reach or impressions.','Процент пользователей, взаимодействующих с контентом (лайки, комментарии, репосты, клики) относительно охвата или показов.','La percentuale di utenti che interagiscono con il contenuto rispetto alla portata o alle impressioni totali.','El porcentaje de usuarios que interactúan con el contenido en relación al alcance o impresiones totales.','النسبة المئوية للمستخدمين الذين يتفاعلون مع المحتوى نسبة إلى إجمالي الوصول أو مرات الظهور.','Le pourcentage d\'utilisateurs interagissant avec le contenu par rapport à la portée ou aux impressions totales.'),
    origin: g('Social media metric; became a key indicator with the rise of platforms like Facebook, Instagram, and TikTok.','Метрика социальных сетей; стала ключевым показателем с ростом платформ Facebook, Instagram и TikTok.','Metrica dei social media; diventata indicatore chiave con la crescita di Facebook, Instagram e TikTok.','Métrica de redes sociales; se convirtió en indicador clave con el crecimiento de Facebook, Instagram y TikTok.','مقياس وسائل التواصل الاجتماعي؛ أصبح مؤشرًا رئيسيًا مع نمو Facebook وInstagram وTikTok.','Métrique des réseaux sociaux ; devenue un indicateur clé avec la montée de Facebook, Instagram et TikTok.') },
  { term: 'Frequency Capping',
    definition: g('A limit on the number of times a single user sees the same ad within a time period to prevent ad fatigue.','Ограничение количества раз, которое один пользователь видит одну и ту же рекламу, чтобы предотвратить усталость.','Un limite al numero di volte che un singolo utente vede lo stesso annuncio per prevenire la fatica pubblicitaria.','Un límite en el número de veces que un usuario ve el mismo anuncio para prevenir la fatiga publicitaria.','حد على عدد المرات التي يرى فيها مستخدم واحد نفس الإعلان لمنع إجهاد الإعلان.','Une limite du nombre de fois qu\'un utilisateur voit la même publicité pour éviter la lassitude publicitaire.'),
    origin: g('Developed as an optimization technique; helps maintain ad effectiveness and positive brand perception.','Разработано как техника оптимизации; помогает поддерживать эффективность рекламы и позитивное восприятие бренда.','Sviluppata come tecnica di ottimizzazione; mantiene l\'efficacia dell\'annuncio e la percezione positiva del brand.','Desarrollado como técnica de optimización; mantiene la efectividad del anuncio y la percepción positiva de la marca.','تم تطويره كتقنية للتحسين؛ يساعد في الحفاظ على فعالية الإعلان والتصور الإيجابي للعلامة التجارية.','Développée comme technique d\'optimisation ; maintient l\'efficacité publicitaire et la perception positive de la marque.') },
  { term: 'Funnel',
    definition: g('The journey a customer takes from first awareness to final conversion, visualized as a narrowing funnel.','Путь клиента от первого ознакомления до финальной конверсии, визуализируемый как сужающаяся воронка.','Il percorso del cliente dalla prima consapevolezza alla conversione finale, visualizzato come un imbuto.','El viaje del cliente desde la primera conciencia hasta la conversión final, visualizado como un embudo.','الرحلة التي يقطعها العميل من الوعي الأول إلى التحويل النهائي، يُصوَّر كقمع يضيق.','Le parcours d\'un client depuis la première prise de conscience jusqu\'à la conversion finale, visualisé comme un entonnoir.'),
    origin: g('Derived from the AIDA model (Attention, Interest, Desire, Action) developed in the late 19th century.','Происходит от модели AIDA, разработанной в конце 19 века.','Derivato dal modello AIDA sviluppato alla fine del XIX secolo.','Derivado del modelo AIDA desarrollado a finales del siglo XIX.','مشتق من نموذج AIDA الذي تم تطويره في أواخر القرن التاسع عشر.','Dérivé du modèle AIDA développé à la fin du XIXe siècle.') },
  { term: 'Geo-Targeting',
    definition: g('Delivering ads to users based on their geographic location, from country-level to neighborhood-level.','Показ рекламы пользователям на основе их географического местоположения, от уровня страны до района.','Distribuzione di annunci agli utenti in base alla loro posizione geografica, dal livello nazionale a quello di quartiere.','Entrega de anuncios a usuarios basándose en su ubicación geográfica, desde nivel país hasta barrio.','عرض الإعلانات للمستخدمين بناءً على موقعهم الجغرافي، من مستوى الدولة إلى مستوى الحي.','Diffusion de publicités aux utilisateurs selon leur localisation géographique, du niveau national au niveau du quartier.'),
    origin: g('Enabled by IP geolocation and mobile GPS; essential for local business advertising.','Стало возможным благодаря геолокации по IP и GPS мобильных устройств.','Reso possibile dalla geolocalizzazione IP e dal GPS mobile.','Habilitado por geolocalización IP y GPS móvil.','أتاحه تحديد الموقع الجغرافي بواسطة IP وGPS للهواتف المحمولة.','Rendu possible par la géolocalisation IP et le GPS mobile.') },
  { term: 'Impression',
    definition: g('A single instance of an ad being displayed to a user. One view = one impression.','Единичный случай показа рекламы пользователю. Один просмотр = один показ.','Un\'unica istanza di un annuncio mostrato a un utente. Una visualizzazione = un\'impressione.','Una instancia única de un anuncio mostrado a un usuario. Una vista = una impresión.','مثيل واحد لعرض إعلان على مستخدم. مشاهدة واحدة = ظهور واحد.','Une instance unique d\'affichage d\'une publicité. Une vue = une impression.'),
    origin: g('From print advertising where "impressions" referred to the number of times ink was pressed onto paper.','Из печатной рекламы, где «impressions» означало количество оттисков на бумаге.','Dalla pubblicità stampata dove "impressioni" si riferiva al numero di stampe sulla carta.','De la publicidad impresa donde "impresiones" se refería al número de prensados de tinta.','من الإعلان المطبوع حيث كانت "الانطباعات" تشير إلى عدد مرات الطباعة.','De la publicité imprimée où les « impressions » désignaient le nombre de fois l\'encre était pressée.') },
  { term: 'KPI (Key Performance Indicator)',
    definition: g('A measurable value that demonstrates how effectively a company is achieving its business objectives.','Измеримое значение, демонстрирующее эффективность достижения бизнес-целей.','Un valore misurabile che dimostra l\'efficacia nel raggiungere gli obiettivi aziendali.','Un valor medible que demuestra la efectividad en lograr los objetivos comerciales.','قيمة قابلة للقياس توضح مدى فعالية تحقيق الأهداف التجارية.','Une valeur mesurable démontrant l\'efficacité dans l\'atteinte des objectifs.'),
    origin: g('Management concept formalized in the 20th century; widely adopted across industries.','Управленческая концепция, формализованная в 20 веке; широко применяется во всех отраслях.','Concetto di gestione formalizzato nel XX secolo; ampiamente adottato in tutti i settori.','Concepto de gestión formalizado en el siglo XX; ampliamente adoptado en todas las industrias.','مفهوم إداري تم تقنينه في القرن العشرين؛ يُستخدم على نطاق واسع.','Concept de gestion formalisé au XXe siècle ; largement adopté dans tous les secteurs.') },
  { term: 'Landing Page',
    definition: g('A standalone web page specifically designed for a marketing campaign, where visitors "land" after clicking an ad.','Отдельная веб-страница, специально разработанная для маркетинговой кампании, на которую попадают посетители после клика по рекламе.','Una pagina web autonoma progettata specificamente per una campagna di marketing, dove i visitatori "atterrano" dopo aver cliccato un annuncio.','Una página web independiente diseñada para una campaña de marketing, donde los visitantes "aterrizan" después de hacer clic en un anuncio.','صفحة ويب مستقلة مصممة خصيصًا لحملة تسويقية، حيث "يهبط" الزوار بعد النقر على إعلان.','Une page web autonome conçue pour une campagne marketing, où les visiteurs « atterrissent » après avoir cliqué sur une publicité.'),
    origin: g('Term coined in the early 2000s with the rise of PPC advertising and dedicated campaign pages.','Термин появился в начале 2000-х с ростом PPC-рекламы и выделенных страниц кампаний.','Termine coniato nei primi anni 2000 con la crescita della pubblicità PPC.','Término acuñado a principios de los 2000 con el auge de la publicidad PPC.','صُكَّ المصطلح في أوائل الألفية مع نمو إعلانات PPC.','Terme apparu au début des années 2000 avec la montée de la publicité PPC.') },
  { term: 'Lead',
    definition: g('A potential customer who has shown interest by providing contact information or taking a qualifying action.','Потенциальный клиент, проявивший интерес, предоставив контактные данные или совершив квалифицирующее действие.','Un potenziale cliente che ha mostrato interesse fornendo informazioni di contatto o compiendo un\'azione qualificante.','Un cliente potencial que ha mostrado interés proporcionando información de contacto o tomando una acción calificadora.','عميل محتمل أبدى اهتمامه من خلال تقديم معلومات الاتصال أو اتخاذ إجراء مؤهل.','Un client potentiel ayant montré son intérêt en fournissant ses coordonnées.'),
    origin: g('Sales terminology; in digital marketing, typically captured via forms, sign-ups, or chat interactions.','Термин из продаж; в цифровом маркетинге фиксируется через формы, регистрации или чат.','Terminologia delle vendite; nel marketing digitale, acquisito tramite moduli o iscrizioni.','Terminología de ventas; en marketing digital, capturado a través de formularios o registros.','مصطلح من المبيعات؛ في التسويق الرقمي، يتم التقاطه عبر النماذج أو التسجيلات.','Terminologie commerciale ; en marketing digital, capturé via des formulaires ou inscriptions.') },
  { term: 'LTV (Lifetime Value)',
    definition: g('The total revenue a business can expect from a single customer over the entire duration of their relationship.','Общий доход, который бизнес может ожидать от одного клиента за всё время их отношений.','Il ricavo totale che un\'azienda può aspettarsi da un singolo cliente durante l\'intera durata del rapporto.','Los ingresos totales que una empresa puede esperar de un solo cliente durante toda la relación.','إجمالي الإيرادات التي يمكن أن تتوقعها الشركة من عميل واحد طوال مدة العلاقة.','Le revenu total qu\'une entreprise peut attendre d\'un client sur toute la durée de la relation.'),
    origin: g('Business metric from subscription models; critical for determining sustainable customer acquisition costs.','Бизнес-метрика из подписочных моделей; критически важна для определения устойчивых затрат на привлечение.','Metrica aziendale dai modelli di abbonamento; critica per determinare i costi sostenibili di acquisizione.','Métrica empresarial de modelos de suscripción; crítica para determinar costos sostenibles de adquisición.','مقياس أعمال من نماذج الاشتراك؛ حاسم لتحديد تكاليف الاستحواذ المستدامة.','Métrique commerciale des modèles d\'abonnement ; essentielle pour déterminer les coûts d\'acquisition durables.') },
  { term: 'Lookalike Audience',
    definition: g('A targeting method that finds new users resembling your existing customers based on demographics, interests, and behavior.','Метод таргетирования, находящий новых пользователей, похожих на существующих клиентов по демографии, интересам и поведению.','Un metodo di targeting che trova nuovi utenti simili ai clienti esistenti per dati demografici, interessi e comportamento.','Un método de segmentación que encuentra nuevos usuarios similares a tus clientes existentes.','طريقة استهداف تجد مستخدمين جددًا يشبهون عملاءك الحاليين.','Une méthode de ciblage qui trouve de nouveaux utilisateurs ressemblant à vos clients existants.'),
    origin: g('Popularized by Facebook (Meta) Ads around 2013 as a powerful targeting feature.','Популяризировано платформой Facebook (Meta) Ads примерно в 2013 году.','Reso popolare da Facebook (Meta) Ads intorno al 2013.','Popularizado por Facebook (Meta) Ads alrededor de 2013.','انتشر من خلال إعلانات Facebook (Meta) حوالي عام 2013.','Popularisé par Facebook (Meta) Ads vers 2013.') },
  { term: 'Pixel',
    definition: g('A small piece of code placed on a website that tracks user actions and sends data back to the ad platform.','Небольшой фрагмент кода на сайте, который отслеживает действия пользователей и отправляет данные на рекламную платформу.','Un piccolo pezzo di codice inserito in un sito web che traccia le azioni degli utenti e invia dati alla piattaforma pubblicitaria.','Un pequeño fragmento de código en un sitio web que rastrea las acciones de los usuarios y envía datos a la plataforma de anuncios.','جزء صغير من الكود يُوضع على موقع ويب يتتبع إجراءات المستخدمين ويرسل البيانات إلى منصة الإعلانات.','Un petit morceau de code placé sur un site web qui suit les actions des utilisateurs et envoie les données à la plateforme publicitaire.'),
    origin: g('Named after the original 1×1 transparent pixel image used for tracking; now refers to JavaScript-based tracking code.','Назван в честь оригинального прозрачного пикселя 1×1, используемого для отслеживания; теперь означает код отслеживания на JavaScript.','Prende il nome dall\'immagine pixel 1×1 trasparente originariamente usata per il tracciamento; ora si riferisce a codice JavaScript.','Nombrado por la imagen pixel transparente 1×1 original usada para rastreo; ahora se refiere a código JavaScript.','سُمي بناءً على صورة البكسل الشفاف 1×1 الأصلية المستخدمة للتتبع؛ يشير الآن إلى كود JavaScript.','Nommé d\'après l\'image pixel 1×1 transparente originale ; désigne maintenant un code de suivi JavaScript.') },
  { term: 'PPC (Pay-Per-Click)',
    definition: g('An advertising model where the advertiser pays only when a user clicks on their ad.','Модель рекламы, при которой рекламодатель платит только тогда, когда пользователь кликает по его рекламе.','Un modello pubblicitario in cui l\'inserzionista paga solo quando un utente clicca sul suo annuncio.','Un modelo publicitario donde el anunciante paga solo cuando un usuario hace clic en su anuncio.','نموذج إعلاني يدفع فيه المعلن فقط عندما ينقر المستخدم على إعلانه.','Un modèle publicitaire où l\'annonceur ne paie que lorsqu\'un utilisateur clique sur sa publicité.'),
    origin: g('Pioneered by GoTo.com (later Overture) in 1998; Google AdWords adopted it in 2000.','Впервые введено GoTo.com (позже Overture) в 1998 году; Google AdWords перенял его в 2000 году.','Introdotto da GoTo.com (poi Overture) nel 1998; adottato da Google AdWords nel 2000.','Introducido por GoTo.com (luego Overture) en 1998; Google AdWords lo adoptó en 2000.','ابتكره GoTo.com (لاحقاً Overture) في 1998؛ اعتمده Google AdWords في 2000.','Introduit par GoTo.com (devenu Overture) en 1998 ; adopté par Google AdWords en 2000.') },
  { term: 'Quality Score',
    definition: g('A rating by Google Ads (1-10) that estimates the quality and relevance of your ads, keywords, and landing pages.','Оценка Google Ads (1-10), которая определяет качество и релевантность рекламы, ключевых слов и посадочных страниц.','Una valutazione di Google Ads (1-10) che stima la qualità e la pertinenza dei tuoi annunci, parole chiave e pagine di destinazione.','Una calificación de Google Ads (1-10) que estima la calidad y relevancia de tus anuncios, palabras clave y páginas de destino.','تصنيف من Google Ads (1-10) يقدّر جودة وملاءمة إعلاناتك وكلماتك المفتاحية وصفحات الهبوط.','Une note de Google Ads (1-10) estimant la qualité et la pertinence de vos publicités, mots-clés et pages d\'atterrissage.'),
    origin: g('Introduced by Google AdWords in 2005 to improve ad relevance and user experience in search results.','Введено Google AdWords в 2005 году для улучшения релевантности рекламы и пользовательского опыта в результатах поиска.','Introdotto da Google AdWords nel 2005 per migliorare la pertinenza degli annunci nei risultati di ricerca.','Introducido por Google AdWords en 2005 para mejorar la relevancia de los anuncios en resultados de búsqueda.','قدمه Google AdWords في 2005 لتحسين ملاءمة الإعلانات في نتائج البحث.','Introduit par Google AdWords en 2005 pour améliorer la pertinence des publicités dans les résultats de recherche.') },
  { term: 'Reach',
    definition: g('The total number of unique users who have seen your ad at least once.','Общее количество уникальных пользователей, которые увидели вашу рекламу хотя бы один раз.','Il numero totale di utenti unici che hanno visto il tuo annuncio almeno una volta.','El número total de usuarios únicos que han visto tu anuncio al menos una vez.','العدد الإجمالي للمستخدمين الفريدين الذين شاهدوا إعلانك مرة واحدة على الأقل.','Le nombre total d\'utilisateurs uniques ayant vu votre publicité au moins une fois.'),
    origin: g('Traditional broadcast metric adapted for digital media; distinguishes unique viewers from total impressions.','Традиционная метрика вещания, адаптированная для цифровых медиа; отличает уникальных зрителей от общего числа показов.','Metrica broadcast tradizionale adattata per i media digitali.','Métrica de transmisión tradicional adaptada para medios digitales.','مقياس بث تقليدي تم تكييفه للوسائط الرقمية.','Métrique de diffusion traditionnelle adaptée aux médias numériques.') },
  { term: 'Retargeting (Remarketing)',
    definition: g('Showing ads to users who have previously visited your website or interacted with your content.','Показ рекламы пользователям, которые ранее посещали ваш сайт или взаимодействовали с контентом.','Mostrare annunci agli utenti che hanno precedentemente visitato il tuo sito o interagito con i tuoi contenuti.','Mostrar anuncios a usuarios que previamente visitaron tu sitio web o interactuaron con tu contenido.','عرض إعلانات للمستخدمين الذين سبق لهم زيارة موقعك أو التفاعل مع المحتوى.','Afficher des publicités aux utilisateurs ayant visité votre site ou interagi avec votre contenu.'),
    origin: g('Enabled by tracking cookies and pixels; became mainstream around 2010 with platforms like AdRoll and Google Ads.','Стало возможным благодаря куки и пикселям; стало массовым примерно в 2010 году.','Reso possibile dai cookie e pixel di tracciamento; diventato mainstream intorno al 2010.','Habilitado por cookies y píxeles; se volvió popular alrededor de 2010.','أتاحته ملفات تعريف الارتباط وبكسلات التتبع؛ أصبح شائعًا حوالي 2010.','Rendu possible par les cookies et pixels ; devenu courant vers 2010.') },
  { term: 'ROAS (Return On Ad Spend)',
    definition: g('The revenue generated for every dollar spent on advertising. Calculated as revenue / ad spend.','Доход, полученный на каждый доллар рекламных расходов. Рассчитывается как доход / расходы на рекламу.','Il ricavo generato per ogni dollaro speso in pubblicità. Calcolato come ricavi / spesa pubblicitaria.','Los ingresos generados por cada dólar gastado en publicidad. Calculado como ingresos / gasto publicitario.','الإيرادات المتولدة عن كل دولار يُنفق على الإعلان. تُحسب كـ إيرادات / إنفاق إعلاني.','Le revenu généré pour chaque dollar dépensé en publicité. Calculé comme revenu / dépenses publicitaires.'),
    origin: g('E-commerce metric evolved from traditional ROI; specifically measures advertising efficiency.','Метрика электронной коммерции, развившаяся из ROI; специально измеряет эффективность рекламы.','Metrica e-commerce evoluta dal ROI tradizionale; misura specificamente l\'efficienza pubblicitaria.','Métrica de e-commerce que evolucionó del ROI; mide específicamente la eficiencia publicitaria.','مقياس التجارة الإلكترونية تطور من ROI؛ يقيس كفاءة الإعلان تحديدًا.','Métrique e-commerce issue du ROI ; mesure spécifiquement l\'efficacité publicitaire.') },
  { term: 'ROI (Return On Investment)',
    definition: g('A measure of the profitability of an investment. Calculated as (net profit / cost of investment) × 100.','Мера прибыльности инвестиций. Рассчитывается как (чистая прибыль / стоимость инвестиций) × 100.','Una misura della redditività di un investimento. Calcolato come (profitto netto / costo dell\'investimento) × 100.','Una medida de la rentabilidad de una inversión. Calculado como (beneficio neto / costo de inversión) × 100.','مقياس لربحية الاستثمار. يُحسب كـ (صافي الربح / تكلفة الاستثمار) × 100.','Une mesure de la rentabilité d\'un investissement. Calculé comme (bénéfice net / coût) × 100.'),
    origin: g('Financial metric used since the early 20th century; adapted broadly across all business functions.','Финансовая метрика, используемая с начала 20 века; широко адаптирована.','Metrica finanziaria utilizzata dall\'inizio del XX secolo; ampiamente adattata.','Métrica financiera utilizada desde principios del siglo XX; ampliamente adaptada.','مقياس مالي يُستخدم منذ أوائل القرن العشرين؛ تم تكييفه على نطاق واسع.','Métrique financière utilisée depuis le début du XXe siècle ; largement adoptée.') },
  { term: 'SEM (Search Engine Marketing)',
    definition: g('A form of digital marketing that promotes websites by increasing their visibility in search engine results through paid advertising.','Форма цифрового маркетинга, продвигающая сайты путём повышения видимости в результатах поиска через платную рекламу.','Una forma di marketing digitale che promuove i siti web aumentandone la visibilità nei risultati dei motori di ricerca.','Una forma de marketing digital que promueve sitios web aumentando su visibilidad en resultados de búsqueda mediante publicidad pagada.','شكل من أشكال التسويق الرقمي يروج للمواقع عن طريق زيادة ظهورها في نتائج محركات البحث من خلال الإعلانات المدفوعة.','Une forme de marketing digital qui promeut les sites web en augmentant leur visibilité dans les résultats de recherche via la publicité payante.'),
    origin: g('Evolved alongside search engines in the late 1990s; originally included both SEO and paid search.','Развивалось вместе с поисковыми системами в конце 1990-х; изначально включало SEO и платный поиск.','Evoluto insieme ai motori di ricerca alla fine degli anni \'90.','Evolucionó junto con los motores de búsqueda a finales de los 90.','تطور جنبًا إلى جنب مع محركات البحث في أواخر التسعينيات.','A évolué avec les moteurs de recherche à la fin des années 1990.') },
  { term: 'SEO (Search Engine Optimization)',
    definition: g('The practice of optimizing a website to improve its ranking in organic (unpaid) search engine results.','Практика оптимизации сайта для улучшения его позиций в органической (бесплатной) поисковой выдаче.','La pratica di ottimizzare un sito web per migliorarne il posizionamento nei risultati organici dei motori di ricerca.','La práctica de optimizar un sitio web para mejorar su posición en los resultados orgánicos de los motores de búsqueda.','ممارسة تحسين موقع الويب لتحسين ترتيبه في نتائج محركات البحث العضوية (غير المدفوعة).','La pratique d\'optimisation d\'un site web pour améliorer son classement dans les résultats organiques des moteurs de recherche.'),
    origin: g('Originated in the mid-1990s as webmasters began optimizing pages for early search engines like AltaVista.','Возникло в середине 1990-х, когда веб-мастера начали оптимизировать страницы для ранних поисковых систем.','Originato a metà degli anni \'90 quando i webmaster iniziarono a ottimizzare le pagine per i primi motori di ricerca.','Se originó a mediados de los 90 cuando los webmasters comenzaron a optimizar páginas para los primeros motores de búsqueda.','نشأ في منتصف التسعينيات عندما بدأ مشرفو المواقع في تحسين الصفحات لمحركات البحث المبكرة.','Apparu au milieu des années 1990 quand les webmasters ont commencé à optimiser les pages pour les premiers moteurs de recherche.') },
  { term: 'Split Test',
    definition: g('Another term for A/B testing; comparing two or more variations of an ad or page to find the best performer.','Другое название A/B-тестирования; сравнение двух или более вариаций рекламы или страницы.','Un altro termine per A/B testing; confronto di due o più varianti di un annuncio o pagina per trovare la migliore.','Otro término para pruebas A/B; comparar dos o más variaciones de un anuncio o página para encontrar la mejor.','مصطلح آخر لاختبار A/B؛ مقارنة نسختين أو أكثر من إعلان أو صفحة لإيجاد الأفضل.','Un autre terme pour le test A/B ; comparaison de deux variantes ou plus d\'une publicité ou page.'),
    origin: g('From experimental design methodology; "split" refers to dividing traffic between variations.','Из методологии экспериментального дизайна; «split» означает разделение трафика между вариациями.','Dalla metodologia del design sperimentale; "split" si riferisce alla divisione del traffico tra varianti.','De la metodología de diseño experimental; "split" se refiere a dividir el tráfico entre variaciones.','من منهجية التصميم التجريبي؛ "split" يشير إلى تقسيم حركة المرور بين المتغيرات.','De la méthodologie de conception expérimentale ; « split » désigne la division du trafic entre les variantes.') },
  { term: 'UTM Parameters',
    definition: g('Tags added to URLs to track the effectiveness of marketing campaigns across traffic sources.','Теги, добавляемые к URL для отслеживания эффективности маркетинговых кампаний по источникам трафика.','Tag aggiunti agli URL per tracciare l\'efficacia delle campagne di marketing attraverso le fonti di traffico.','Etiquetas añadidas a las URLs para rastrear la efectividad de las campañas de marketing.','علامات تُضاف إلى عناوين URL لتتبع فعالية حملات التسويق عبر مصادر حركة المرور.','Des balises ajoutées aux URLs pour suivre l\'efficacité des campagnes marketing.'),
    origin: g('UTM stands for "Urchin Tracking Module," named after Urchin Software — later acquired by Google and became Google Analytics.','UTM означает "Urchin Tracking Module", названный по имени Urchin Software — позже приобретённого Google.','UTM sta per "Urchin Tracking Module", dal software Urchin — acquisito da Google e diventato Google Analytics.','UTM significa "Urchin Tracking Module", nombrado por Urchin Software — adquirido por Google y convertido en Google Analytics.','UTM تعني "Urchin Tracking Module"، سُمّيت على اسم Urchin Software — استحوذت عليها Google لاحقًا.','UTM signifie « Urchin Tracking Module », d\'après Urchin Software — racheté par Google, devenu Google Analytics.') },
];

export default function GlossaryPage() {
  const { t, language } = useLanguage();
  const [search, setSearch] = useState('');

  const sorted = useMemo(() => {
    const filtered = glossaryData.filter(entry =>
      entry.term.toLowerCase().includes(search.toLowerCase()) ||
      (entry.definition[language] || entry.definition.en).toLowerCase().includes(search.toLowerCase())
    );
    return filtered.sort((a, b) => a.term.localeCompare(b.term));
  }, [search, language]);

  return (
    <motion.div variants={container} initial="hidden" animate="show" className="space-y-6">
      <motion.div variants={item}>
        <h1 className="text-2xl font-bold text-foreground">{t('glossary.title')}</h1>
        <p className="text-muted-foreground text-sm mt-1">{t('glossary.subtitle')}</p>
      </motion.div>

      <motion.div variants={item}>
        <div className="relative max-w-md">
          <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground" />
          <Input
            placeholder={t('glossary.searchPlaceholder')}
            className="pl-9"
            value={search}
            onChange={(e) => setSearch(e.target.value)}
          />
        </div>
      </motion.div>

      <motion.div variants={item} className="space-y-3">
        {sorted.length === 0 ? (
          <div className="flex flex-col items-center justify-center py-20 text-center">
            <BookOpen className="h-12 w-12 text-muted-foreground mb-3" />
            <p className="text-muted-foreground">{t('glossary.noResults')}</p>
          </div>
        ) : (
          sorted.map((entry) => (
            <Card key={entry.term} className="glass-card">
              <CardContent className="py-4 px-5">
                <h3 className="font-bold text-foreground text-base mb-1">{entry.term}</h3>
                <p className="text-sm text-foreground/80 mb-3">
                  {entry.definition[language] || entry.definition.en}
                </p>
                <div className="rounded-lg bg-secondary/30 px-3 py-2">
                  <p className="text-xs text-muted-foreground">
                    <span className="font-semibold text-primary">{t('glossary.origin')}:</span>{' '}
                    {entry.origin[language] || entry.origin.en}
                  </p>
                </div>
              </CardContent>
            </Card>
          ))
        )}
      </motion.div>
    </motion.div>
  );
}
