import { useState, useMemo } from 'react';
import { useLanguage } from '@/i18n/LanguageContext';
import { motion } from 'framer-motion';
import { BookOpen, Search } from 'lucide-react';
import { Input } from '@/components/ui/input';
import { Card, CardContent } from '@/components/ui/card';

const container = { hidden: { opacity: 0 }, show: { opacity: 1, transition: { staggerChildren: 0.02 } } };
const item = { hidden: { opacity: 0, y: 8 }, show: { opacity: 1, y: 0 } };

interface GlossaryEntry {
  term: string;
  definition: Record<string, string>;
  origin: Record<string, string>;
}

const glossaryData: GlossaryEntry[] = [
  { term: 'A/B Testing',
    definition: { en: 'A method of comparing two versions of a webpage or ad to determine which one performs better.', ru: 'Метод сравнения двух версий веб-страницы или рекламы для определения, какая работает лучше.', it: 'Un metodo per confrontare due versioni di una pagina web o annuncio per determinare quale funziona meglio.', es: 'Un método para comparar dos versiones de una página web o anuncio para determinar cuál funciona mejor.', ar: 'طريقة لمقارنة نسختين من صفحة ويب أو إعلان لتحديد أيهما أفضل أداءً.', fr: "Une méthode de comparaison de deux versions d'une page web ou d'une publicité pour déterminer laquelle est la plus performante." },
    origin: { en: 'From statistical hypothesis testing; A and B represent the control and variant groups.', ru: 'Из статистического тестирования гипотез; A и B обозначают контрольную и тестовую группы.', it: 'Dal test di ipotesi statistiche; A e B rappresentano i gruppi di controllo e variante.', es: 'De las pruebas de hipótesis estadísticas; A y B representan los grupos de control y variante.', ar: 'من اختبار الفرضيات الإحصائية؛ A وB يمثلان مجموعتي التحكم والمتغير.', fr: "De l'analyse statistique ; A et B représentent les groupes contrôle et variant." } },
  { term: 'CPA (Cost Per Acquisition)',
    definition: { en: 'The total cost of acquiring one customer through a specific campaign or channel.', ru: 'Общая стоимость привлечения одного клиента через конкретную кампанию или канал.', it: "Il costo totale per acquisire un cliente attraverso una campagna o un canale specifico.", es: 'El costo total de adquirir un cliente a través de una campaña o canal específico.', ar: 'التكلفة الإجمالية للحصول على عميل واحد من خلال حملة أو قناة محددة.', fr: "Le coût total d'acquisition d'un client via une campagne ou un canal spécifique." },
    origin: { en: 'Digital marketing metric; measures efficiency of spend in converting prospects to customers.', ru: 'Метрика цифрового маркетинга; измеряет эффективность расходов на конверсию потенциальных клиентов.', it: 'Metrica del marketing digitale; misura l\'efficienza della spesa nella conversione dei prospect in clienti.', es: 'Métrica de marketing digital; mide la eficiencia del gasto en la conversión de prospectos a clientes.', ar: 'مقياس التسويق الرقمي؛ يقيس كفاءة الإنفاق في تحويل العملاء المحتملين إلى عملاء فعليين.', fr: 'Métrique de marketing digital ; mesure l\'efficacité des dépenses pour convertir les prospects en clients.' } },
  { term: 'CPC (Cost Per Click)',
    definition: { en: 'The amount paid each time a user clicks on an ad. Calculated as total spend divided by number of clicks.', ru: 'Сумма, которая оплачивается каждый раз, когда пользователь кликает по рекламе. Рассчитывается как общие расходы, делённые на количество кликов.', it: "L'importo pagato ogni volta che un utente clicca su un annuncio. Calcolato come spesa totale divisa per il numero di clic.", es: 'La cantidad pagada cada vez que un usuario hace clic en un anuncio. Calculado como el gasto total dividido por el número de clics.', ar: 'المبلغ المدفوع في كل مرة ينقر فيها المستخدم على إعلان. يُحسب بقسمة إجمالي الإنفاق على عدد النقرات.', fr: "Le montant payé chaque fois qu'un utilisateur clique sur une publicité. Calculé comme le total des dépenses divisé par le nombre de clics." },
    origin: { en: 'Originated with pay-per-click advertising models pioneered by search engines in the early 2000s.', ru: 'Возникло с моделями рекламы с оплатой за клик, введёнными поисковыми системами в начале 2000-х.', it: 'Originato dai modelli pubblicitari pay-per-click introdotti dai motori di ricerca nei primi anni 2000.', es: 'Se originó con los modelos de publicidad de pago por clic introducidos por los motores de búsqueda a principios de los 2000.', ar: 'نشأ مع نماذج إعلانات الدفع بالنقرة التي قدمتها محركات البحث في أوائل العقد الأول من الألفية.', fr: 'Né avec les modèles publicitaires au coût par clic introduits par les moteurs de recherche au début des années 2000.' } },
  { term: 'CPL (Cost Per Lead)',
    definition: { en: 'The cost incurred for each lead generated. Calculated as total spend divided by number of leads.', ru: 'Стоимость каждого полученного лида. Рассчитывается как общие расходы, делённые на количество лидов.', it: 'Il costo sostenuto per ogni lead generato. Calcolato come spesa totale divisa per il numero di lead.', es: 'El costo incurrido por cada lead generado. Calculado como el gasto total dividido por el número de leads.', ar: 'التكلفة المتكبدة لكل عميل محتمل تم توليده. تُحسب بقسمة إجمالي الإنفاق على عدد العملاء المحتملين.', fr: 'Le coût engendré pour chaque lead généré. Calculé comme le total des dépenses divisé par le nombre de leads.' },
    origin: { en: 'Key performance metric in lead generation campaigns, especially in B2B marketing.', ru: 'Ключевая метрика эффективности в кампаниях по генерации лидов, особенно в B2B маркетинге.', it: 'Metrica chiave di performance nelle campagne di lead generation, soprattutto nel marketing B2B.', es: 'Métrica clave de rendimiento en campañas de generación de leads, especialmente en marketing B2B.', ar: 'مقياس أداء رئيسي في حملات توليد العملاء المحتملين، خاصة في التسويق بين الشركات.', fr: 'Métrique clé de performance dans les campagnes de génération de leads, surtout en marketing B2B.' } },
  { term: 'CPM (Cost Per Mille)',
    definition: { en: 'The cost per 1,000 impressions of an ad. Calculated as (spend / impressions) × 1000.', ru: 'Стоимость за 1000 показов рекламы. Рассчитывается как (расходы / показы) × 1000.', it: 'Il costo per 1.000 impressioni di un annuncio. Calcolato come (spesa / impressioni) × 1000.', es: 'El costo por 1,000 impresiones de un anuncio. Calculado como (gasto / impresiones) × 1000.', ar: 'التكلفة لكل 1,000 ظهور للإعلان. تُحسب كـ (الإنفاق / مرات الظهور) × 1000.', fr: "Le coût pour 1 000 impressions d'une publicité. Calculé comme (dépenses / impressions) × 1000." },
    origin: { en: '"Mille" is Latin for "thousand." Adopted from traditional media buying where ad rates were quoted per thousand viewers.', ru: '"Mille" — латинское слово для "тысяча". Заимствовано из традиционной медиазакупки, где стоимость рассчитывалась на тысячу зрителей.', it: '"Mille" è il latino per "mille". Adottato dall\'acquisto tradizionale di media dove i tassi pubblicitari erano quotati per mille spettatori.', es: '"Mille" es latín para "mil". Adoptado de la compra de medios tradicional donde las tarifas publicitarias se cotizaban por cada mil espectadores.', ar: '"Mille" كلمة لاتينية تعني "ألف". تم اعتمادها من شراء الوسائط التقليدية حيث كانت أسعار الإعلانات تُحسب لكل ألف مشاهد.', fr: '"Mille" vient du latin « mille ». Adopté de l\'achat média traditionnel où les tarifs étaient exprimés pour mille spectateurs.' } },
  { term: 'CTR (Click-Through Rate)',
    definition: { en: 'The percentage of people who click on an ad after seeing it. Calculated as (clicks / impressions) × 100.', ru: 'Процент людей, которые кликнули по рекламе после её просмотра. Рассчитывается как (клики / показы) × 100.', it: "La percentuale di persone che cliccano su un annuncio dopo averlo visto. Calcolato come (clic / impressioni) × 100.", es: 'El porcentaje de personas que hacen clic en un anuncio después de verlo. Calculado como (clics / impresiones) × 100.', ar: 'النسبة المئوية للأشخاص الذين ينقرون على إعلان بعد مشاهدته. تُحسب كـ (النقرات / مرات الظهور) × 100.', fr: "Le pourcentage de personnes qui cliquent sur une publicité après l'avoir vue. Calculé comme (clics / impressions) × 100." },
    origin: { en: 'One of the earliest digital advertising metrics, dating back to the first banner ad era in the mid-1990s.', ru: 'Одна из первых метрик цифровой рекламы, восходящая к эпохе первых баннерных объявлений в середине 1990-х.', it: 'Una delle prime metriche della pubblicità digitale, risalente all\'era dei primi banner pubblicitari a metà degli anni \'90.', es: 'Una de las primeras métricas de publicidad digital, que se remonta a la era de los primeros banners a mediados de los 90.', ar: 'أحد أقدم مقاييس الإعلان الرقمي، يعود إلى عصر أولى إعلانات البانر في منتصف التسعينيات.', fr: "L'une des premières métriques de la publicité numérique, datant de l'ère des premiers banners au milieu des années 1990." } },
  { term: 'Conversion',
    definition: { en: 'When a user completes a desired action such as filling out a form, making a purchase, or signing up.', ru: 'Когда пользователь совершает целевое действие: заполняет форму, совершает покупку или регистрируется.', it: "Quando un utente completa un'azione desiderata come compilare un modulo, effettuare un acquisto o registrarsi.", es: 'Cuando un usuario completa una acción deseada como llenar un formulario, realizar una compra o registrarse.', ar: 'عندما يكمل المستخدم إجراءً مرغوبًا مثل ملء نموذج أو إجراء عملية شراء أو التسجيل.', fr: "Lorsqu'un utilisateur effectue une action souhaitée comme remplir un formulaire, effectuer un achat ou s'inscrire." },
    origin: { en: 'Marketing term borrowed from sales; refers to converting a prospect into a customer or lead.', ru: 'Маркетинговый термин, заимствованный из продаж; означает конверсию потенциального клиента в покупателя или лид.', it: 'Termine di marketing preso dalle vendite; si riferisce alla conversione di un prospect in un cliente o lead.', es: 'Término de marketing tomado de ventas; se refiere a convertir un prospecto en un cliente o lead.', ar: 'مصطلح تسويقي مستعار من المبيعات؛ يشير إلى تحويل عميل محتمل إلى عميل فعلي.', fr: 'Terme marketing emprunté aux ventes ; fait référence à la conversion d\'un prospect en client ou lead.' } },
  { term: 'Funnel',
    definition: { en: 'The journey a customer takes from first awareness to final conversion, typically visualized as a narrowing funnel.', ru: 'Путь клиента от первого ознакомления до финальной конверсии, обычно визуализируемый как сужающаяся воронка.', it: 'Il percorso che un cliente compie dalla prima consapevolezza alla conversione finale, tipicamente visualizzato come un imbuto che si restringe.', es: 'El viaje que un cliente realiza desde la primera conciencia hasta la conversión final, típicamente visualizado como un embudo que se estrecha.', ar: 'الرحلة التي يقطعها العميل من الوعي الأول إلى التحويل النهائي، وعادة ما يتم تصورها كقمع يضيق.', fr: "Le parcours d'un client depuis la première prise de conscience jusqu'à la conversion finale, généralement visualisé comme un entonnoir." },
    origin: { en: 'Derived from the AIDA model (Attention, Interest, Desire, Action) developed in the late 19th century.', ru: 'Происходит от модели AIDA (Внимание, Интерес, Желание, Действие), разработанной в конце 19 века.', it: 'Derivato dal modello AIDA (Attenzione, Interesse, Desiderio, Azione) sviluppato alla fine del XIX secolo.', es: 'Derivado del modelo AIDA (Atención, Interés, Deseo, Acción) desarrollado a finales del siglo XIX.', ar: 'مشتق من نموذج AIDA (الانتباه، الاهتمام، الرغبة، العمل) الذي تم تطويره في أواخر القرن التاسع عشر.', fr: 'Dérivé du modèle AIDA (Attention, Intérêt, Désir, Action) développé à la fin du XIXe siècle.' } },
  { term: 'Impression',
    definition: { en: 'A single instance of an ad being displayed to a user. One view = one impression.', ru: 'Единичный случай показа рекламы пользователю. Один просмотр = один показ.', it: "Un'unica istanza di un annuncio mostrato a un utente. Una visualizzazione = un'impressione.", es: 'Una instancia única de un anuncio mostrado a un usuario. Una vista = una impresión.', ar: 'مثيل واحد لعرض إعلان على مستخدم. مشاهدة واحدة = ظهور واحد.', fr: "Une instance unique d'affichage d'une publicité à un utilisateur. Une vue = une impression." },
    origin: { en: 'From print advertising where "impressions" referred to the number of times a printing plate pressed ink onto paper.', ru: 'Из печатной рекламы, где «impressions» означало количество раз, когда печатная форма наносила чернила на бумагу.', it: 'Dalla pubblicità stampata dove "impressioni" si riferiva al numero di volte in cui una lastra di stampa premeva l\'inchiostro sulla carta.', es: 'De la publicidad impresa donde "impresiones" se refería al número de veces que una placa de impresión presionaba tinta sobre el papel.', ar: 'من الإعلان المطبوع حيث كانت "الانطباعات" تشير إلى عدد المرات التي ضغطت فيها لوحة الطباعة الحبر على الورق.', fr: "De la publicité imprimée où les « impressions » désignaient le nombre de fois qu'une plaque d'impression pressait l'encre sur le papier." } },
  { term: 'KPI (Key Performance Indicator)',
    definition: { en: 'A measurable value that demonstrates how effectively a company is achieving its business objectives.', ru: 'Измеримое значение, демонстрирующее, насколько эффективно компания достигает своих бизнес-целей.', it: "Un valore misurabile che dimostra quanto efficacemente un'azienda sta raggiungendo i suoi obiettivi aziendali.", es: 'Un valor medible que demuestra qué tan efectivamente una empresa está logrando sus objetivos comerciales.', ar: 'قيمة قابلة للقياس توضح مدى فعالية الشركة في تحقيق أهدافها التجارية.', fr: "Une valeur mesurable qui démontre l'efficacité avec laquelle une entreprise atteint ses objectifs." },
    origin: { en: 'Management concept formalized in the 20th century; widely adopted across industries for performance tracking.', ru: 'Управленческая концепция, формализованная в 20 веке; широко применяется для отслеживания эффективности.', it: 'Concetto di gestione formalizzato nel XX secolo; ampiamente adottato in tutti i settori per il monitoraggio delle performance.', es: 'Concepto de gestión formalizado en el siglo XX; ampliamente adoptado en todas las industrias para el seguimiento del rendimiento.', ar: 'مفهوم إداري تم تقنينه في القرن العشرين؛ واعتُمد على نطاق واسع لتتبع الأداء.', fr: 'Concept de gestion formalisé au XXe siècle ; largement adopté dans tous les secteurs pour le suivi de la performance.' } },
  { term: 'Lead',
    definition: { en: 'A potential customer who has shown interest by providing contact information or taking a qualifying action.', ru: 'Потенциальный клиент, проявивший интерес, предоставив контактные данные или совершив квалифицирующее действие.', it: "Un potenziale cliente che ha mostrato interesse fornendo informazioni di contatto o compiendo un'azione qualificante.", es: 'Un cliente potencial que ha mostrado interés proporcionando información de contacto o tomando una acción calificadora.', ar: 'عميل محتمل أبدى اهتمامه من خلال تقديم معلومات الاتصال أو اتخاذ إجراء مؤهل.', fr: "Un client potentiel qui a montré son intérêt en fournissant ses coordonnées ou en effectuant une action qualifiante." },
    origin: { en: 'Sales terminology; in digital marketing, typically captured via forms, sign-ups, or chat interactions.', ru: 'Термин из продаж; в цифровом маркетинге обычно фиксируется через формы, регистрации или чат-взаимодействия.', it: 'Terminologia delle vendite; nel marketing digitale, tipicamente acquisito tramite moduli, iscrizioni o interazioni in chat.', es: 'Terminología de ventas; en marketing digital, típicamente capturado a través de formularios, registros o interacciones de chat.', ar: 'مصطلح من المبيعات؛ في التسويق الرقمي، يتم التقاطه عادة عبر النماذج أو التسجيلات أو تفاعلات الدردشة.', fr: 'Terminologie commerciale ; en marketing digital, généralement capturé via des formulaires, inscriptions ou interactions de chat.' } },
  { term: 'Lookalike Audience',
    definition: { en: 'A targeting method that finds new users who resemble your existing customers based on demographics, interests, and behavior.', ru: 'Метод таргетирования, который находит новых пользователей, похожих на ваших существующих клиентов по демографии, интересам и поведению.', it: 'Un metodo di targeting che trova nuovi utenti simili ai tuoi clienti esistenti in base a dati demografici, interessi e comportamento.', es: 'Un método de segmentación que encuentra nuevos usuarios que se parecen a tus clientes existentes según demografía, intereses y comportamiento.', ar: 'طريقة استهداف تجد مستخدمين جددًا يشبهون عملاءك الحاليين بناءً على الخصائص الديموغرافية والاهتمامات والسلوك.', fr: 'Une méthode de ciblage qui trouve de nouveaux utilisateurs ressemblant à vos clients existants selon la démographie, les intérêts et le comportement.' },
    origin: { en: 'Popularized by Facebook (Meta) Ads platform around 2013 as a powerful targeting feature.', ru: 'Популяризировано платформой Facebook (Meta) Ads примерно в 2013 году как мощная функция таргетинга.', it: 'Reso popolare dalla piattaforma Facebook (Meta) Ads intorno al 2013 come potente funzionalità di targeting.', es: 'Popularizado por la plataforma Facebook (Meta) Ads alrededor de 2013 como una potente función de segmentación.', ar: 'انتشر من خلال منصة إعلانات Facebook (Meta) حوالي عام 2013 كميزة استهداف قوية.', fr: 'Popularisé par la plateforme publicitaire Facebook (Meta) vers 2013 comme fonctionnalité de ciblage puissante.' } },
  { term: 'Reach',
    definition: { en: 'The total number of unique users who have seen your ad at least once.', ru: 'Общее количество уникальных пользователей, которые увидели вашу рекламу хотя бы один раз.', it: 'Il numero totale di utenti unici che hanno visto il tuo annuncio almeno una volta.', es: 'El número total de usuarios únicos que han visto tu anuncio al menos una vez.', ar: 'العدد الإجمالي للمستخدمين الفريدين الذين شاهدوا إعلانك مرة واحدة على الأقل.', fr: "Le nombre total d'utilisateurs uniques qui ont vu votre publicité au moins une fois." },
    origin: { en: 'Traditional broadcast metric adapted for digital media; distinguishes unique viewers from total impressions.', ru: 'Традиционная метрика вещания, адаптированная для цифровых медиа; отличает уникальных зрителей от общего числа показов.', it: 'Metrica tradizionale della trasmissione adattata per i media digitali; distingue gli spettatori unici dalle impressioni totali.', es: 'Métrica de transmisión tradicional adaptada para medios digitales; distingue espectadores únicos de impresiones totales.', ar: 'مقياس بث تقليدي تم تكييفه للوسائط الرقمية؛ يميز المشاهدين الفريدين عن إجمالي مرات الظهور.', fr: 'Métrique de diffusion traditionnelle adaptée aux médias numériques ; distingue les téléspectateurs uniques des impressions totales.' } },
  { term: 'Retargeting (Remarketing)',
    definition: { en: 'Showing ads to users who have previously visited your website or interacted with your content.', ru: 'Показ рекламы пользователям, которые ранее посещали ваш сайт или взаимодействовали с вашим контентом.', it: 'Mostrare annunci agli utenti che hanno precedentemente visitato il tuo sito web o interagito con i tuoi contenuti.', es: 'Mostrar anuncios a usuarios que previamente visitaron tu sitio web o interactuaron con tu contenido.', ar: 'عرض إعلانات للمستخدمين الذين سبق لهم زيارة موقعك الإلكتروني أو التفاعل مع المحتوى الخاص بك.', fr: "Afficher des publicités aux utilisateurs qui ont précédemment visité votre site web ou interagi avec votre contenu." },
    origin: { en: 'Technology enabled by tracking cookies and pixels; became mainstream around 2010 with platforms like AdRoll and Google Ads.', ru: 'Технология, основанная на отслеживающих куки и пикселях; стала массовой примерно в 2010 году с платформами AdRoll и Google Ads.', it: 'Tecnologia abilitata dai cookie e dai pixel di tracciamento; è diventata mainstream intorno al 2010 con piattaforme come AdRoll e Google Ads.', es: 'Tecnología habilitada por cookies de seguimiento y píxeles; se volvió popular alrededor de 2010 con plataformas como AdRoll y Google Ads.', ar: 'تقنية أتاحتها ملفات تعريف الارتباط وبكسلات التتبع؛ أصبحت شائعة حوالي عام 2010 مع منصات مثل AdRoll وGoogle Ads.', fr: 'Technologie rendue possible par les cookies et pixels de suivi ; devenue courante vers 2010 avec des plateformes comme AdRoll et Google Ads.' } },
  { term: 'ROAS (Return On Ad Spend)',
    definition: { en: 'The revenue generated for every dollar spent on advertising. Calculated as revenue / ad spend.', ru: 'Доход, полученный на каждый доллар, потраченный на рекламу. Рассчитывается как доход / рекламные расходы.', it: 'Il ricavo generato per ogni dollaro speso in pubblicità. Calcolato come ricavi / spesa pubblicitaria.', es: 'Los ingresos generados por cada dólar gastado en publicidad. Calculado como ingresos / gasto publicitario.', ar: 'الإيرادات المتولدة عن كل دولار يُنفق على الإعلان. تُحسب كـ إيرادات / إنفاق إعلاني.', fr: 'Le revenu généré pour chaque dollar dépensé en publicité. Calculé comme revenu / dépenses publicitaires.' },
    origin: { en: 'E-commerce metric that evolved from traditional ROI; specifically measures advertising efficiency.', ru: 'Метрика электронной коммерции, которая развилась из традиционного ROI; специально измеряет эффективность рекламы.', it: "Metrica dell'e-commerce evoluta dal ROI tradizionale; misura specificamente l'efficienza pubblicitaria.", es: 'Métrica de comercio electrónico que evolucionó del ROI tradicional; mide específicamente la eficiencia publicitaria.', ar: 'مقياس التجارة الإلكترونية الذي تطور من العائد على الاستثمار التقليدي؛ يقيس كفاءة الإعلان تحديدًا.', fr: "Métrique e-commerce issue du ROI traditionnel ; mesure spécifiquement l'efficacité publicitaire." } },
  { term: 'ROI (Return On Investment)',
    definition: { en: 'A measure of the profitability of an investment. Calculated as (net profit / cost of investment) × 100.', ru: 'Мера прибыльности инвестиций. Рассчитывается как (чистая прибыль / стоимость инвестиций) × 100.', it: "Una misura della redditività di un investimento. Calcolato come (profitto netto / costo dell'investimento) × 100.", es: 'Una medida de la rentabilidad de una inversión. Calculado como (beneficio neto / costo de inversión) × 100.', ar: 'مقياس لربحية الاستثمار. يُحسب كـ (صافي الربح / تكلفة الاستثمار) × 100.', fr: "Une mesure de la rentabilité d'un investissement. Calculé comme (bénéfice net / coût de l'investissement) × 100." },
    origin: { en: 'Financial metric used since the early 20th century; adapted broadly across all business functions.', ru: 'Финансовая метрика, используемая с начала 20 века; широко адаптирована во всех бизнес-функциях.', it: "Metrica finanziaria utilizzata dall'inizio del XX secolo; ampiamente adattata in tutte le funzioni aziendali.", es: 'Métrica financiera utilizada desde principios del siglo XX; adaptada ampliamente en todas las funciones empresariales.', ar: 'مقياس مالي يُستخدم منذ أوائل القرن العشرين؛ تم تكييفه على نطاق واسع عبر جميع وظائف الأعمال.', fr: "Métrique financière utilisée depuis le début du XXe siècle ; largement adoptée dans toutes les fonctions d'entreprise." } },
  { term: 'UTM Parameters',
    definition: { en: 'Tags added to URLs to track the effectiveness of marketing campaigns across traffic sources.', ru: 'Теги, добавляемые к URL для отслеживания эффективности маркетинговых кампаний по источникам трафика.', it: 'Tag aggiunti agli URL per tracciare l\'efficacia delle campagne di marketing attraverso le fonti di traffico.', es: 'Etiquetas añadidas a las URLs para rastrear la efectividad de las campañas de marketing a través de fuentes de tráfico.', ar: 'علامات تُضاف إلى عناوين URL لتتبع فعالية حملات التسويق عبر مصادر حركة المرور.', fr: "Des balises ajoutées aux URLs pour suivre l'efficacité des campagnes marketing à travers les sources de trafic." },
    origin: { en: 'UTM stands for "Urchin Tracking Module," named after Urchin Software — later acquired by Google and became Google Analytics.', ru: 'UTM означает "Urchin Tracking Module", названный по имени Urchin Software — позже приобретённого Google, который стал Google Analytics.', it: 'UTM sta per "Urchin Tracking Module", dal nome di Urchin Software — successivamente acquisito da Google e diventato Google Analytics.', es: 'UTM significa "Urchin Tracking Module", nombrado así por Urchin Software — luego adquirido por Google y que se convirtió en Google Analytics.', ar: 'UTM تعني "Urchin Tracking Module"، سُمّيت على اسم Urchin Software — التي استحوذت عليها Google لاحقًا وأصبحت Google Analytics.', fr: 'UTM signifie « Urchin Tracking Module », nommé d\'après Urchin Software — racheté par Google et devenu Google Analytics.' } },
];

export default function GlossaryPage() {
  const { t, language } = useLanguage();
  const [search, setSearch] = useState('');

  const sorted = useMemo(() => {
    const filtered = glossaryData.filter(entry =>
      entry.term.toLowerCase().includes(search.toLowerCase()) ||
      (entry.definition[language] || entry.definition.en).toLowerCase().includes(search.toLowerCase())
    );
    return filtered.sort((a, b) => a.term.localeCompare(b.term));
  }, [search, language]);

  return (
    <motion.div variants={container} initial="hidden" animate="show" className="space-y-6">
      <motion.div variants={item}>
        <h1 className="text-2xl font-bold text-foreground">{t('glossary.title')}</h1>
        <p className="text-muted-foreground text-sm mt-1">{t('glossary.subtitle')}</p>
      </motion.div>

      <motion.div variants={item}>
        <div className="relative max-w-md">
          <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground" />
          <Input
            placeholder={t('glossary.searchPlaceholder')}
            className="pl-9"
            value={search}
            onChange={(e) => setSearch(e.target.value)}
          />
        </div>
      </motion.div>

      <motion.div variants={item} className="space-y-3">
        {sorted.length === 0 ? (
          <div className="flex flex-col items-center justify-center py-20 text-center">
            <BookOpen className="h-12 w-12 text-muted-foreground mb-3" />
            <p className="text-muted-foreground">{t('glossary.noResults')}</p>
          </div>
        ) : (
          sorted.map((entry) => (
            <Card key={entry.term} className="glass-card">
              <CardContent className="py-4 px-5">
                <h3 className="font-bold text-foreground text-base mb-1">{entry.term}</h3>
                <p className="text-sm text-foreground/80 mb-3">
                  {entry.definition[language] || entry.definition.en}
                </p>
                <div className="rounded-lg bg-secondary/30 px-3 py-2">
                  <p className="text-xs text-muted-foreground">
                    <span className="font-semibold text-primary">{t('glossary.origin')}:</span>{' '}
                    {entry.origin[language] || entry.origin.en}
                  </p>
                </div>
              </CardContent>
            </Card>
          ))
        )}
      </motion.div>
    </motion.div>
  );
}
